language: node_js

node_js:
  - '12'
  - '10'
  - '8'

jobs:
  include:
    - stage: test
      after_success:
        - cat ./coverage/lcov.info | coveralls
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/